---

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/singhsurya1012/TravelBinge
          search-paths:          - ConfigData
          
          
server:
  port: 8001