---

server:
  port: 8100
  servlet:
    context-path: /travelBinge
  error: 
    whitelabel: 
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  
spring:
  application: 
    name: auth-service
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/travelbinge?searchpath=MainSchema
    username: surya
    password: Surya123
  jpa:
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp: 
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none 
  devtools:
    restart:
      trigger-file: /AuthService/src/main/java/com/travelbinge/AuthServiceApplication.java  
      
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
