---
   
server:
  port: 8000
  servlet:
    context-path: /travelbinge
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health,routes,filters
    
spring:
  application:
    name: GATEWAY-SERVER
  mvc:
    servlet:
      load-on-startup: 1    
       
zuul:
  ribbon:
    eager-load:
      enabled: true    
  ignored-services: '*'
  routes:
    auth-service:
      path: /auth/**
      sensitive-headers: Cookie,Set-Cookie
      service-id: AUTH-SERVICE
      strip-prefix: false
    user-service:
      path: /user/**
      service-id: USER-SERVICE
      strip-prefix: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
  
logging: 
  level: 
    org: 
      springframework: 
        security: DEBUG